### PR TITLE
[WIP] Update to current Open PS2 Loader codebase

### PR DESCRIPTION
**Pull request by citronalco**
I have merged the current (17efb447b77442e1a85715d194c3d7b4b5ad0b94, as of 2023-09-11) ps2homebrew Open PS2 Loader codebase.

Regarding the languages files:
I simply took the translated strings that are relevant for OPL-DB and appended them to ps2homebrew OPL's lang files.
If some other strings got changes in the past, this changes are gone. IMHO they should be given upstream, to ps2homebrew OPL, anyway.
The lang repo is here: https://github.com/citronalco/OPL-Daily-Builds-lang
If you would like to take over this repo, too: The URL is set in [download_lng.sh](https://github.com/citronalco/OPL-Daily-Builds/commit/f6084c537dbae597d5a1b3d0feeffb0586cf7d84#diff-5dceb2205ddcf4174770f3f018cd8f0ae02d3ba6ef01c0cafee8d07471db3024)

The whole thing builds and runs in pcsx2, but is otherwise untested.

I had to change the makefile of elfldr to get it to compile with the current ps2sdk, see 79a59297c6ff2da8689fbc42fa4523a181a33ce7. I'm neither a programmer nor do I have much clue about compilers, so I do not know if that changes make sense or might cause trouble.

EDIT: Seems like it causes trouble: Starting ELF applications works, but Popstarter does not. When trying to start a PS1 game, Popstarter does not start but the screen gets black. Though Popstarter starts on PCSX2.

### CODE REVIEW

**Comment by citronalco** [comment]
My guess is, that elfldr does not work any more because I had to change the compiler flags.
Tried today to replace it with the built in one, which looks very similar. Could not get it to work so far.

This is the first time I do stuff for PS2, so I still have to figure out how to get the debug builds to display anything on ps2link's ps2client, or how to do dome other (probably) basic stuff.

**Comment by citronalco** [comment]
Current state: Popstarter starts in PCSX2, but not on real hardware (black screen). I have no clue why, and **need help** here.
Everything else looks pretty fine.

**Comment by 10522** [comment]
@citronalco, create a topic on PS2-Home, maybe someone can help you. Also maybe these users can help too: 

@Jay-Jay-OPL, @danielb7390, @RickyL1213, @YAGAMI55

**Comment by citronalco** [comment]
@10522 
I tried to create a topic on PS2-Home, but seems like I'm not allowed to post links there, so it got blocked.
Already created a support ticket there two weeks ago, but unfortunately got no response.

If you can (and want to) create a topic on PS2-Home: Feel free and go ahead. I will join the thread then.

**Comment by 10522** [comment]
@citronalco, links can be left in the comments to the topic. Try creating a topic without links, and then add a link in the first comment.

**Comment by citronalco** [comment]
@10522, tried to start a topic without links now. Let's hope forum moderation is more gracious this time!

**Comment by citronalco** [comment]
I tried to start a new topic on PS2-HOME now for the third time. Answered the auto-questions, left out any URLs, tried to open a support ticket to register as a developer - nothing worked. Either no response, or "blocked by moderator". I give up.

@10522 (or anyone else reading this), could you please start a topic and maybe post the link here? I'll happily reply on it then!

**Comment by TnA-Plastic** [comment]
Join the PS2-Scene-Discord. The PS2-Home-Staff blocked my reply, due to it supposedly violating the rules...

**Comment by TnA-Plastic** [comment]
Oh! So it should be up-to-date with the newest official OPL Beta build?

**Comment by 10522** [comment]
@TnA-Plastic 

Check out [this](https://github.com/citronalco/OPL-Daily-Builds/issues/3#issuecomment-2295383091). Also please write to @tihmstar so that he adds [this](https://tinyurl.com/mvvy986a) and [this](https://tinyurl.com/bddthfkb) PR to his fork and also about [this](https://tinyurl.com/yvhwfxa7). This is necessary so that it would be possible to use [UDPBD + USB](https://www.psx-place.com/threads/mx4sio-force-opl-to-ignore-inserted-usb-flash.42644/#post-379503) at the same time.

**Pull request closed without merging**
